# Generated by Django 3.2.7 on 2021-09-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=100)),
                ('sender_id', models.IntegerField()),
                ('receiver_id', models.IntegerField()),
                ('requisition_id', models.IntegerField()),
                ('status', models.TextField(default='A', max_length=10)),
            ],
            options={
                'db_table': 'chat',
            },
        ),
        migrations.CreateModel(
            name='ChatMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_msg', models.TextField(max_length=100)),
                ('symbol', models.TextField(max_length=100)),
                ('status', models.TextField(max_length=10)),
            ],
            options={
                'db_table': 'chat_msg',
            },
        ),
    ]
